{% set name = "GCR" %}
{% set version = "0.8.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GCR-{{ version }}.tar.gz
  sha256: a42247adaa0689034504b809afed737ffdaee545297f6a3d62b34ef206b14ad7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - easyquery >=0.1.3
    - numpy
    - python >=3.6

test:
  imports:
    - GCR
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yymao/generic-catalog-reader
  summary: 'Generic Catalog Reader: A common reader interface for accessing generic catalogs'
  license: MIT
  license_file: LICENSE
  doc_url: https://yymao.github.io/generic-catalog-reader/
  dev_url: https://github.com/yymao/generic-catalog-reader

extra:
  recipe-maintainers:
    - yymao
