{% set name = "GCR" %}
{% set version = "0.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/GCR-{{ version }}.tar.gz
  sha256: 37af25abb56e60f134ab6ce79c2c564b64f63c480e1962a1b24435488a3058a2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - easyquery >=0.1.3
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - GCR
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yymao/generic-catalog-reader
  summary: 'Generic Catalog Reader: A common reader interface for accessing generic catalogs'
  license: MIT
  license_file: LICENSE
  doc_url: https://yymao.github.io/generic-catalog-reader/
  dev_url: https://github.com/yymao/generic-catalog-reader

extra:
  recipe-maintainers:
    - yymao
